### ISSUE TITLE
Explain relationship between controller documents and JOSE headers

### ISSUE THREAD

**Issue by andresuribe87** [w3c/vc-jose-cose#106] opened 2023-06-09 22:16 UTC
Just read that section, and I have to say that it's not intuitive at all. I think it would be worth either: adding an example that refers to this controller document, pointing to the spec you mentioned, or explicitly stating the relationship between controller docs and  `iss` & `kid`.

_Originally posted by @andresuribe87 in https://github.com/w3c/vc-jwt/pull/104#discussion_r1224839405_

**Comment by OR13** [comment] 2023-06-11 13:53
Dupe of / related to....:

- https://github.com/w3c/vc-jwt/issues/31
- https://github.com/w3c/vc-jwt/issues/30
- https://github.com/w3c/vc-jwt/issues/22
- https://github.com/w3c/vc-jwt/issues/83

cc @mprorock @selfissued @Sakurann this keeps coming up, it would be nice if one of you would open a PR to resolve.

**Comment by OR13** [comment] 2023-06-11 16:35
<img width="1826" alt="Screen Shot 2023-06-11 at 11 34 26 AM" src="https://github.com/w3c/vc-jwt/assets/8295856/a442c352-c8be-4b88-98c8-91a3c7c6fedf">

**Comment by OR13** [comment] 2023-06-11 16:48
<img width="1827" alt="Screen Shot 2023-06-11 at 11 47 40 AM" src="https://github.com/w3c/vc-jwt/assets/8295856/02117539-0b59-493a-9349-1d209b8ae9e0">

**Comment by selfissued** [comment] 2023-09-11 14:19
PR #144 will address this issue.

**Comment by iherman** [comment] 2023-09-15 05:55
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-14-vcwg#section6-13) on 2023-09-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 6.13. Explain relationship between controller documents and JOSE headers (issue vc-jose-cose#106)

_See github issue [vc-jose-cose#106](https://github.com/w3c/vc-jose-cose/issues/106)._




**Michael Jones:** overtaken by the decision to re-do controller doc PR.  

</details>

**Comment by OR13** [comment] 2023-09-29 19:51
I think this has been addressed.

**Closed by OR13** 2023-09-29 19:51 UTC
Labels: has-pr, before-CR
